services:
  - type: web
    name: forex-telegram-bot
    env: python
    pythonVersion: "3.11"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    healthCheckPath: /health
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false # Keep your token secret
      - key: EXCHANGERATE_API_KEY
        sync: false # Keep your API key secret
      - key: DATABASE_URL
        fromDatabase:
          name: forex-bot-db # Replace with your Render database name
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "8000"
      - key: RELOAD
        value: "false"

databases:
  - name: forex-bot-db
    databaseName: forex_bot_db
    user: forex_bot_user
    plan: free # Or your preferred plan