services:
  - type: web
    name: forex-telegram-bot
    env: python
    pythonVersion: 3.12.6
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    healthCheckPath: /health
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false # Keep your token secret
      - key: EXCHANGERATE_API_KEY
        sync: false # Keep your API key secret
      - key: DATABASE_URL
        fromDatabase:
          name: forex-bot-db # Replace with your Render database name
          property: connectionString
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "8000"
      - key: RELOAD
        value: "false"
      # RENDER_EXTERNAL_URL is automatically set by Render
      # This tells the API service to use the production URL instead of localhost
      # For local development, this will be empty and the service will use http://127.0.0.1:8000
      - key: RENDER_EXTERNAL_URL
        value: "https://forex-bot1.onrender.com" # Your actual Render URL

databases:
  - name: forex-bot-db
    databaseName: forex_bot_db
    user: forex_bot_user
    plan: free # Or your preferred plan