services:
  - type: web
    name: forex-bot
    env: python
    pythonVersion: "3.11"
    buildCommand: |
      pip install --upgrade pip
      pip install setuptools wheel
      pip install -r requirements.txt
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    plan: free