global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'forexbot'
    static_configs:
      - targets: ['bot:8000']
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:9187']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121'] 